spring:
  application:
    name: md-analytics
  datasource:
    url: jdbc:postgresql://localhost:5432/md_db
    username: md_user
    password: md_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

md:
  aggregator:
    intervals:
      - id: "1m"
        seconds: 60
      - id: "1s"
        seconds: 1

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
