services:
  md-collector-simulator:
    build:
      context: ../md-collector-simulator
      dockerfile: Dockerfile
    container_name: md-collector-simulator
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CONFIG_IMPORT: "optional:configserver:http://md-config-server:8888"
    networks:
      - md-net

  md-collector-binance:
    build:
      context: ../md-collector-binance
      dockerfile: Dockerfile
    container_name: md-collector-binance
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CONFIG_IMPORT: "optional:configserver:http://md-config-server:8888"
    networks:
      - md-net

  md-aggregator:
    build:
      context: ../md-aggregator
      dockerfile: Dockerfile
    container_name: md-aggregator
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CONFIG_IMPORT: "optional:configserver:http://md-config-server:8888"
    networks:
      - md-net

  md-analytics:
    build:
      context: ../md-analytics
      dockerfile: Dockerfile
    container_name: md-analytics
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CONFIG_IMPORT: "optional:configserver:http://md-config-server:8888"
    ports:
      - "8080:8080"
    networks:
      - md-net
networks:
  md-net:
    driver: bridge