version: '3.9'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: md-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - md-net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: md-kafka
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - md-net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: md-kafka-ui
    depends_on:
      - kafka
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - md-net

  kafka-init:
    image: bitnami/kafka:latest
    container_name: kafka-init
    depends_on:
      kafka:
        condition: service_started
    volumes:
      - ./kafka-init.sh:/usr/bin/kafka-init.sh
    networks:
      - md-net
    command: [ "/usr/bin/kafka-init.sh" ]

  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: md-timescaledb
    environment:
      POSTGRES_DB: md_db
      POSTGRES_USER: md_user
      POSTGRES_PASSWORD: md_password
    ports:
      - "5432:5432"
    networks:
      - md-net

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.108.0
    container_name: md-otel-collector
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml:ro
    ports:
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP (optional)
    networks:
      - md-net

  jaeger:
    image: jaegertracing/all-in-one:1.57
    container_name: md-jaeger
    ports:
      - "16686:16686"   # UI
      - "14250:14250"   # OTLP gRPC
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    networks:
      - md-net

networks:
  md-net:
    driver: bridge
