spring:
  application:
    name: md-load-test

md:
  load:
    threads: 10
    requestsPerThread: 100
    symbol: BTC-USD
    interval: 1m
    from: 1764470000
    to: 1764480000
    verboseErrors: false
  analytics:
    base-url: http://localhost:8080

management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4317
