spring:
  application:
    name: md-collector-binance
  kafka:
    bootstrap-servers: localhost:9093
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

md:
  collector:
    binance:
      symbols:
        btcusdt: BTC-USD
        ethusdt: ETH-USD
        solusdt: SOL-USD
        bnbusdt: BNB-USD
      reconnectDelaySeconds: 5
      wsBase: wss://stream.binance.com:9443/ws

management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4317
